import markdown
from bs4 import BeautifulSoup

# Read the ./rules.md file
with open('./rules.md', 'r', encoding='utf-8') as f:
    content = f.read()

# Convert Markdown to HTML
html_content = markdown.markdown(content, extensions=['toc', 'attr_list', 'tables', 'fenced_code'])

# Use BeautifulSoup to parse the HTML and extract headers
soup = BeautifulSoup(html_content, 'html.parser')

# Function to build a nested TOC from the headers
def build_toc(soup):
    toc = []
    current_level = 0
    stack = []
    
    # Maintain counters for each header level (h1, h2, etc.)
    level_counters = [0] * 6  # Assuming we may have h1 to h6
    
    for header in soup.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6']):
        level = int(header.name[1])  # Get the header level (1, 2, 3, etc.)
        header_id = header.get('id')  # Use the ID generated by the 'toc' extension
        header_text = header.text  
        
        # Increment the current level counter and reset lower levels
        level_counters[level - 1] += 1
        for i in range(level, 6):
            level_counters[i] = 0
        
        # Build the section number (e.g., 1.1, 1.2, 2.1.1)
        section_number = ".".join(str(c) for c in level_counters[:level] if c > 0)
      
                        
        # Create a list item for the TOC
        li = f'''
        <li>
            <a href="#{header_id}">
                <span class="title">{header_text}<span class="leaders" aria-hidden="true"></span></span>
                <span class="page"><span class="visually-hidden">Page</span> {section_number}</span>
            </a>
        </li>
        '''
        i += 1
        
        # Adjust TOC structure based on the header level
        if level > current_level:
            # Start a new nested list
            toc.append('<ol class="toc-list" role="list">')
            stack.append('</ol>')
        elif level < current_level:
            # Close the previous nested list
            for _ in range(current_level - level):
                toc.append(stack.pop())
        
        toc.append(li)
        current_level = level
    
    # Close any remaining open lists
    while stack:
        toc.append(stack.pop())
    
    return '\n'.join(toc)

# Generate the TOC
toc_html = build_toc(soup)

# Final HTML content with the generated TOC
html = f'''
<html lang="en">

    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
        <title>Eidos - Rules</title>
        <meta name="description" content="Eidos Rulebook">
        <link rel="icon" type="image/x-icon" href="./images/favicon.svg">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <link rel="stylesheet" href="./rules_style.css">

    </head>
    
    <body>
    
        <br>
        <nav>
            <h2>Table of Contents</h2>
            {toc_html}
        </nav>
    
        <article>
            {html_content}
        </article>
    
    </body>

</html>
'''

# Write the final HTML to ./rules.html
with open('./index.html', 'w', encoding='utf-8') as f:
    f.write(html)
