site_name: Eidos - Rules
site_url: https://example.com/
nav:
    - Presentation: index.md
    - 'Character Creation':
        - 'Personality': 'personality.md'      
        - 'Religion and Spirituality': 'religion.md'      
        - 'Physical Description': 'physical.md'      
        - 'Clothing': 'clothing.md'      
        - 'Equipment and Possessions': 'equipment.md'      
        - 'Skills': 'skills.md'
        - 'Background': 'background.md'            
    - Combat: combat.md
    - Health & Survival: health.md
    - DM Tools: dm.md

theme:
    name: mkdocs
    custom_dir: custom_theme/
    
extra_css: [extra.css]

plugins:
  - search