site_name: Eidos - Rules
site_url: https://example.com/
nav:
    - Presentation: 0_index.md
    - 'Character Creation':
        - 'Personality': '1_personality.md'      
        - 'Religion and Spirituality': '2_religion.md'      
        - 'Physical Description': '3_physical.md'      
        - 'Clothing': '4_clothing.md'      
        - 'Equipment and Possessions': '5_equipment.md'      
        - 'Skills': '6_skills.md'
        - 'Background': '7_background.md'            
    - Combat: 8_combat.md
    - Health & Survival: 9_health.md
    - DM Tools: 10_dm.md

theme:
    name: mkdocs
    custom_dir: custom_theme/
    
extra_css: [extra.css]

plugins:
  - search
